version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: back-end/Dockerfile
    env_file:
      - back-end/.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: front-end/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
